version: '3'
services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      # file path where all the files and folders are at
      context: .
      # look in the current directory and find this file
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # don't copy this, doesn't have "."
      - /app/node_modules
      # copy this as signified like the port ". : /app"
      - .:/app
  tests:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    #overrun a command that's already in the Dockerfile
    command: ["npm", "run", "test"]
